export const departamentosCiudades = {
    "Bogotá": ["Bogotá"],
    "Antioquia": ["Medellín", "Envigado", "Rionegro", "Itagüí", "Bello", "La Ceja", "Caldas"],
    "Atlántico": ["Barranquilla", "Soledad", "Malambo", "Puerto Colombia", "Galapa", "Sabanalarga"],
    "Cundinamarca": ["Fusagasugá", "Soacha", "Chía", "Zipaquirá", "Tocancipá", "Madrid", "La Calera"],
    "Valle del Cauca": ["Cali", "Palmira", "Yumbo", "Buenaventura", "Tuluá", "Buga", "Zarzal"],
    "Cesar": ["Valledupar", "Aguachica", "La Paz", "Bosconia", "San Diego"],
    "Bolívar": ["Cartagena", "Magangué", "Sincelejo", "Clemencia", "Arjona", "Mompox"],
    "Santander": ["Bucaramanga", "Cúcuta", "Floridablanca", "Girón", "Piedecuesta", "Barrancabermeja"],
    "Nariño": ["Pasto", "Ipiales", "Tumaco", "Taminango", "La Unión"],
    "Risaralda": ["Pereira", "Dosquebradas", "Santa Rosa de Cabal", "La Virginia"],
    "Cauca": ["Popayán", "Pasto", "Armenia", "Totoró", "El Tambo"],
    "Huila": ["Neiva", "Campoalegre", "Algeciras", "La Plata", "Tello"],
    "Tolima": ["Ibagué", "Espinal", "Melgar", "Honda", "Chaparral"],
    "Meta": ["Villavicencio", "Acacías", "Cumaral", "Granada", "Restrepo"],
    "La Guajira": ["Riohacha", "Maicao", "Fonseca", "San Juan del Cesar"],
    "Casanare": ["Yopal", "Aguazul", "Hato Corozal", "Tauramena", "Maní"],
    "Magdalena": ["Santa Marta", "Ciénaga", "Aracataca", "El Banco", "Fundación"],
    "Putumayo": ["Mocoa", "Villagarzón", "Colón", "San Francisco"],
    "Quindío": ["Armenia", "Circasia", "La Tebaida", "Quimbaya", "Montenegro"],
    "Chocó": ["Quibdó", "Lloró", "Bahía Solano", "Istmina", "Medio Atrato"],
    "Boyacá": ["Tunja", "Duitama", "Sogamoso", "Chiquinquirá", "Paipa", "Moniquirá"],
    "Sucre": ["Sincelejo", "Corozal", "Sampués", "Coveñas", "San Onofre"],
    "Archipiélago de San Andrés, Providencia y Santa Catalina": ["San Andrés", "Providencia"],
    "Norte de Santander": ["Cúcuta", "Pamplona", "Villa del Rosario", "Tibú", "Los Patios"],
    "Caldas": ["Manizales", "Chinchiná", "Villamaría", "Neira", "La Dorada"],
    "Guaviare": ["San José del Guaviare", "Calamar", "El Retorno", "Miraflores"],
    "Guainía": ["Inírida", "San Felipe", "Barrancominas"],
    "Vaupés": ["Mitú", "Carurú", "Papunaua"],
    "Amazonas": ["Leticia", "Puerto Nariño", "Tarapacá"],
    "Vichada": ["Puerto Carreño", "La Primavera", "Cumaribo"],
  };
  